### ISSUE TITLE
Is there a way to allow multiple lines in the Item cells?

### ISSUE THREAD

**Issue by clfristoe** [justinmfischer/SwiftyAccordionCells#3]
I am using your code as the template for an About Page for an app I am developing. Great job on the UI, it really looks great and was exactly what I was looking for. I have the Header cells as the title of a topic and then I would like the Item cell to have the answer, which are multiple lines long. Right now it looks like I can only have two lines though, which isn't enough. Is it possible to allow three or four lines of text?

**Comment by justinmfischer** [comment]
Hi Carly,

Good question, yes its possible and easy to implement. In the view
controller you would modify the code to return UITableViewAutomaticDimension
instead of a fixed size of 44. Once done, simply add auto layout
constraints to each cell as described here.
http://useyourloaf.com/blog/self-sizing-table-view-cells/

   func tableView(tableView: UITableView, heightForRowAtIndexPath
indexPath: NSIndexPath) -> CGFloat {

        let item = self.cells.items[indexPath.row]



        if item is SwiftyAccordionCells.HeaderItem {

            return 60

        } else if (item.isHidden) {

            return 0

        } else {

            return 44

        }

    }

If you make these changes, i would love to pull your changes in and give
you credit for the enhancement!

Thanks,
Justin

**Comment by clfristoe** [comment]
Forgive me as I am still new to github... I made the changes and committed them, but I am unable to push them. I cloned the repo and created a new branch afterwards. Is there something I'm missing?

**Comment by justinmfischer** [comment]
Hi Carly,

Thanks for making the changes. I want to add you as a contributor. Please
create a "pull request" and ill merge in your changes.

Thanks,
Justin

**Comment by clfristoe** [comment]
Created the pull request, thanks for the assistance and the contribution credit.
